language: ruby
rvm:
- 2.0.0
env:
  global:
  - GIT_COMMITTER_NAME=nacyot
  - GIT_COMMITTER_EMAIL=propellerheaven@gmail.com
  - GIT_AUTHOR_NAME=nacyot
  - GIT_AUTHOR_EMAIL=propellerheaven@gmail.com
  - secure: Dnws69bfiB1G40wwPqCB+WNVu4P+UmzAz+Vx6FXyuB/Esxd4goIxchp/2L9Iui/dx8iX31Dk0qsNzkBbGMnqS9Qq8ZzTOgNFIwUyoE1lXH/qYNTI/VOmcYkn3GvRtwRXILmcHvdsFJ4ZwLWGpmstaKpWoDSytBmV3K/6/OV4NPc=
before_script:
- npm install -g bower
- bower install
- git clone https://github.com/dev-study/dev-study.github.io.git build
script: bundle exec middleman build
after_success:
- cd build
- git add -A
- git commit -m 'Update build files'
- printenv
- git push https://$GH_TOKEN@github.com/dev-study/dev-study.github.io.git master
