language: ruby
rvm:
- 2.0.0
env:
  global:
  - secure: zP1fgHsddJK+gv8HbESqoPJ/2v/jHyaOsWYTQn0je7oZNIrxhY4ndEyoKpFNfKO5kzGPsRjVi83f9DlJv2818NDf2b4Z/+apyM4uqPuw472jt0wQg1n7SaISqZHCqbkS746YRquNIX1RhTMImmtBG5DS+nKYjVhl1sbpVYhDjQQ=
  - GIT_COMMITTER_NAME=nacyot
  - GIT_COMMITTER_EMAIL=propellerheaven@gmail.com
  - GIT_AUTHOR_NAME=nacyot
  - GIT_AUTHOR_EMAIL=propellerheaven@gmail.com
before_script:
- npm install -g bower
- bower install
- git clone https://github.com/dev-study/dev-study.github.io.git build
script: bundle exec middleman build
after_success:
- cd build
- git add -A
- git commit -m 'Update build files'
- printenv
- git push https://$GH_TOKEN@github.com/dev-study/dev-study.github.io.git master
