language: ruby
rvm:
- 2.0.0
env:
  global:
  - GIT_COMMITTER_NAME=nacyot
  - GIT_COMMITTER_EMAIL=propellerheaven@gmail.com
  - GIT_AUTHOR_NAME=nacyot
  - GIT_AUTHOR_EMAIL=propellerheaven@gmail.com
  - secure: C1s+z3cZb6bqhZzXlyxBvop0DOxjOuBTFAQs2/lVAV41fI7LHD7aQKU3H2WzqgId+q0hjqb4AscoN2REWb382bN5lVQu8VukbRq28nZUpcaXaXSYk+Uhuk+14Wg4O7BWAxkKqJIoed9wToYVqlhENn7avCG6gF4RR/znQthLceQ=
before_script:
- npm install -g bower
- bower install
- git clone https://github.com/dev-study/dev-study.github.io.git build
script: bundle exec middleman build
after_success:
- cd build
- git add -A
- git commit -m 'Update build files'
- '[ $GIT_COMMITTER ] && echo there is git_committer'
- '[ $GH_TOKEN ] && echo there is Gh_Token'
- '[ "$GIT_COMMITTER" ] && echo there is git_committer'
- '[ "$GH_TOKEN" ] && echo there is Gh_Token'
- 'git push https://"$GH_TOKEN"@github.com/dev-study/dev-study.github.io.git master'
- 'git push https://$GH_TOKEN@github.com/dev-study/dev-study.github.io.git master'
