language: ruby
rvm: 
  - 1.9.3
  - 2.0.0
env:
  global:
    - GIT_COMMITTER_NAME=nacyot
    - GIT_COMMITTER_EMAIL=propellerheaven@gmail.com
    - GIT_AUTHOR_NAME=nacyot
    - GIT_AUTHOR_EMAIL=propellerheaven@gmail.com
    - secure: RRMnULOm144dkFDtKp76UWzNtH3mbv8sEXG1ZRBCftGETUP8ZgHtKuoqkR8OZ21586CCfbvbOmP9q3vi0mEhhk9Jd2W2C66TdCcSA3NGAZQSynPTorVDHx+1tCFyw9IfNSmRbYXA0NvmRa1VxU5mRlYSG00IosyEB2MmfzlbbTk=
before_script:
  - git clone --quiet git@github.com:dev-study/dev-study.github.io.git build
  - pushd build
  - git checkout -b gh-pages
  - popd
script: bundle exec middleman build
after_success:
  - cd build
  - git add -A
  - git commit -m 'Update build files'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/dev-study/dev-study.github.io.git gh-pages 2> /dev/null'
