language: ruby
rvm: 
  - 2.0.0
env:
  global:
    - GIT_COMMITTER_NAME=nacyot
    - GIT_COMMITTER_EMAIL=propellerheaven@gmail.com
    - GIT_AUTHOR_NAME=nacyot
    - GIT_AUTHOR_EMAIL=propellerheaven@gmail.com
    - secure: "POnDEeNTXMeN6CFUuu2Hwo6yP5eZ3LQ0AhV/NmdaGY+wFKSKF3f6KE+3gLextKlGLVb+is7+fgU3jyJeyGrMUXsly08c+5nAiW4Eo6FwmtKkGezwQR1eqkDmIYXVrU03xcdLz1p8sQhZfhYSlVNopNocwtMytfDYDlcH1SdVcNk="
before_script:
  # - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install -g bower
  - bower install
  - git clone --quiet https://github.com/dev-study/dev-study.github.io.source.git build
script: bundle exec middleman build
after_success:
  - cd build
  - git add -A
  - git commit -m 'Update build files'
  - '[ "$TRAVIS_BRANCH" == "source" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/dev-study/dev-study.github.io.git master 2> /dev/null'
