language: ruby
rvm:
- 2.0.0
env:
  global:
  - GIT_COMMITTER_NAME=nacyot
  - GIT_COMMITTER_EMAIL=propellerheaven@gmail.com
  - GIT_AUTHOR_NAME=nacyot
  - GIT_AUTHOR_EMAIL=propellerheaven@gmail.com
  - secure: Dk7Pm+B42E/Byi1BOBFcjqUOLfAGfIm69uDsNLE/4LCGAwKLbac2fTOMkrmYAU+DLPWwgtFvUhjw/ns+98ERENJvuT9k/Y3gTxhU4xxrDLmsdT0a3C8O4A+rCG94vJiK7A3CDEN0NHj/nT6vbH+qH9OpMrSDTYCo4SVifq/3T/c=
before_script:
- npm install -g bower
- bower install
- git clone --quiet https://github.com/dev-study/dev-study.github.io.source.git build
script: bundle exec middleman build
after_success:
- cd build
- git add -A
- git commit -m 'Update build files'
- '[ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/dev-study/dev-study.github.io.git master'
